# Documentation: https://github.com/bcgov/von-agent-template/tree/master/von-x-agent/config

issuers:
  myorg:
    name: my-org-full-name
    abbreviation: my-organization
    url: https://www.my-organization.ca/my-organization-info-page
    email: info@my-organization.ca
    logo_path: ../assets/img/my-organization-logo.jpg
    endpoint: $ENDPOINT_URL

    connection:
      type: TheOrgBook
      api_url: $TOB_API_URL
      sign_target: false

    credential_types:
    - description: The my-registration credential issued by my-organization
      schema: my-registration.my-organization
      issuer_url: $ENDPOINT_URL/my-organization/my-registration
      credential:
        effective_date:
          input: effective_date
          from: claim
        revoked_date:
          input: expiry_date
          from: claim
      topic:
        source_id:
          input: corp_num
          from: claim
        type:
          input: my-registration.my-organization
          from: value
      mapping:
      - model: attribute
        fields:
          type:
            input: corp_num
            from: value
          value:
            input: corp_num
            from: claim
      - model: attribute
        fields:
          type:
            input: registration_date
            from: value
          format:
            input: datetime
            from: value
          value:
            input: registration_date
            from: claim
      - model: name
        fields:
          text:
            input: entity_name
            from: claim
          type:
            input: entity_name
            from: value
      - model: attribute
        fields:
          type:
            input: entity_name_effective
            from: value
          format:
            input: datetime
            from: value
          value:
            input: entity_name_effective
            from: claim
      - model: address
        fields:
          addressee:
            input: addressee
            from: claim
          civic_address:
            input: address_line_1
            from: claim
          city:
            input: city
            from: claim
          province:
            input: province
            from: claim
          postal_code:
            input: postal_code
            from: claim
          country:
            input: country
            from: claim
      - model: attribute
        fields:
          type:
            input: entity_status
            from: value
          value:
            input: entity_status
            from: claim
      - model: attribute
        fields:
          type:
            input: entity_status_effective
            from: value
          format:
            input: datetime
            from: value
          value:
            input: entity_status_effective
            from: claim
      - model: attribute
        fields:
          type:
            input: entity_type
            from: value
          value:
            input: entity_type
            from: claim
      - model: attribute
        fields:
          type:
            input: registered_jurisdiction
            from: value
          value:
            input: registered_jurisdiction
            from: claim
      - model: attribute
        fields:
          type:
            input: effective_date
            from: value
          format:
            input: datetime
            from: value
          value:
            input: effective_date
            from: claim
      - model: attribute
        fields:
          type:
            input: expiry_date
            from: value
          format:
            input: datetime
            from: value
          value:
            input: expiry_date
            from: claim
    - description: The relationship between two organizations
      schema: my-relationship.my-organization
      issuer_url: $ENDPOINT_URL/my-organization/my-relationship
      depends_on:
      - greenlight_registration
      credential:
        effective_date:
          input: effective_date
          from: claim
      topic:
        related_source_id:
          input: associated_corp_num
          from: claim
        related_type:
          input: my-registration.my-organization
          from: value
        source_id:
          input: corp_num
          from: claim
        type:
          input: my-registration.my-organization
          from: value
      cardinality_fields:
        - associated_corp_num
      mapping:
      - model: attribute
        fields:
          type:
            input: corp_num
            from: value
          value:
            input: corp_num
            from: claim
      - model: attribute
        fields:
          type:
            input: associated_corp_num
            from: value
          value:
            input: associated_corp_num
            from: claim
      - model: attribute
        fields:
          type:
            input: associated_registration_name
            from: value
          value:
            input: associated_registration_name
            from: claim
      - model: attribute
        fields:
          type:
            input: relationship
            from: value
          value:
            input: relationship
            from: claim
      - model: attribute
        fields:
          type:
            input: relationship_description
            from: value
          value:
            input: relationship_description
            from: claim
      - model: attribute
        fields:
          type:
            input: relationship_status
            from: value
          value:
            input: relationship_status
            from: claim
      - model: attribute
        fields:
          type:
            input: relationship_status_effective
            from: value
          format:
            input: datetime
            from: value
          value:
            input: relationship_status_effective
            from: claim
      - model: attribute
        fields:
          type:
            input: effective_date
            from: value
          format:
            input: datetime
            from: value
          value:
            input: effective_date
            from: claim
      - model: attribute
        fields:
          type:
            input: expiry_date
            from: value
          format:
            input: datetime
            from: value
          value:
            input: expiry_date
            from: claim
    - description: The my-permit credential issued by my-organization
      schema: my-permit.my-organization
      issuer_url: $ENDPOINT_URL/my-organization/my-permit
      depends_on:
      - greenlight_registration
      credential:
        effective_date:
          input: effective_date
          from: claim
      topic:
        source_id:
          input: corp_num
          from: claim
        type:
          input: my-registration.my-organization
          from: value
      mapping:
      - model: attribute
        fields:
          type:
            input: corp_num
            from: value
          value:
            input: corp_num
            from: claim
      - model: name
        fields:
          text:
            input: entity_name
            from: claim
          type:
            input: entity_name
            from: value
      - model: attribute
        fields:
          type:
            input: permit_id
            from: value
          value:
            input: permit_id
            from: claim
      - model: attribute
        fields:
          type:
            input: permit_type
            from: value
          value:
            input: permit_type
            from: claim
      - model: attribute
        fields:
          type:
            input: permit_issued_date
            from: value
          format:
            input: datetime
            from: value
          value:
            input: permit_issued_date
            from: claim
      - model: attribute
        fields:
          type:
            input: permit_status
            from: value
          value:
            input: permit_status
            from: claim
      - model: attribute
        fields:
          type:
            input: effective_date
            from: value
          format:
            input: datetime
            from: value
          value:
            input: effective_date
            from: claim

verifiers:
  bctob:
    name: BC OrgBook
    alias: tob-agent
    connection:
      type: TheOrgBook
      api_url: $TOB_API_URL
      agent_admin_url: $TOB_AGENT_ADMIN_URL

proof_requests:
  greenlight_registration:
    version: '1.0.0'
    schemas:
      - key:
          did: 6qnvgJtqwK44D8LFYnV5Yf
          name: Registered Corporation
          version: '1.0.3'
        attributes:
          - corp_num
          - legal_name


### eof ###
